spring.application.name=netty-server-internal-flow-using-event-loop
server.port=8081

logging.level.org.springframework.web=DEBUG
logging.level.reactor.netty.http.server=DEBUG
logging.level.reactor.netty.http.server.AccessLog=INFO
logging.level.reactor.netty.channel=DEBUG